[2025-02-09 11:03:15,083: INFO: main: Welcome to the end to end ML project!]
[2025-02-09 23:25:47,910: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-09 23:25:47,920: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-09 23:26:17,783: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-09 23:26:17,784: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-09 23:27:40,463: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-09 23:27:40,465: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-09 23:28:24,684: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-09 23:28:24,686: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-09 23:28:24,688: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-09 23:28:24,689: INFO: common: created directory at: artifacts]
[2025-02-09 23:28:24,690: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-09 23:28:26,886: INFO: 329861637: artifacts/data_ingestion/data.zip download with following info: /nServer: GitHub.com
Date: Mon, 10 Feb 2025 06:28:27 GMT
Content-Type: text/html; charset=utf-8
Vary: X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With
ETag: W/"d3cf088cbb1ff3c3246e956159cb1dcd"
Cache-Control: max-age=0, private, must-revalidate
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
Referrer-Policy: no-referrer-when-downgrade
Content-Security-Policy: default-src 'none'; base-uri 'self'; child-src github.com/assets-cdn/worker/ github.com/webpack/ github.com/assets/ gist.github.com/assets-cdn/worker/; connect-src 'self' uploads.github.com www.githubstatus.com collector.github.com raw.githubusercontent.com api.github.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com *.rel.tunnels.api.visualstudio.com wss://*.rel.tunnels.api.visualstudio.com objects-origin.githubusercontent.com copilot-proxy.githubusercontent.com proxy.individual.githubcopilot.com proxy.business.githubcopilot.com proxy.enterprise.githubcopilot.com *.actions.githubusercontent.com wss://*.actions.githubusercontent.com productionresultssa0.blob.core.windows.net/ productionresultssa1.blob.core.windows.net/ productionresultssa2.blob.core.windows.net/ productionresultssa3.blob.core.windows.net/ productionresultssa4.blob.core.windows.net/ productionresultssa5.blob.core.windows.net/ productionresultssa6.blob.core.windows.net/ productionresultssa7.blob.core.windows.net/ productionresultssa8.blob.core.windows.net/ productionresultssa9.blob.core.windows.net/ productionresultssa10.blob.core.windows.net/ productionresultssa11.blob.core.windows.net/ productionresultssa12.blob.core.windows.net/ productionresultssa13.blob.core.windows.net/ productionresultssa14.blob.core.windows.net/ productionresultssa15.blob.core.windows.net/ productionresultssa16.blob.core.windows.net/ productionresultssa17.blob.core.windows.net/ productionresultssa18.blob.core.windows.net/ productionresultssa19.blob.core.windows.net/ github-production-repository-image-32fea6.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com insights.github.com wss://alive.github.com api.githubcopilot.com api.individual.githubcopilot.com api.business.githubcopilot.com api.enterprise.githubcopilot.com; font-src github.githubassets.com; form-action 'self' github.com gist.github.com copilot-workspace.githubnext.com objects-origin.githubusercontent.com; frame-ancestors 'none'; frame-src viewscreen.githubusercontent.com notebooks.githubusercontent.com; img-src 'self' data: blob: github.githubassets.com media.githubusercontent.com camo.githubusercontent.com identicons.github.com avatars.githubusercontent.com private-avatars.githubusercontent.com github-cloud.s3.amazonaws.com objects.githubusercontent.com secured-user-images.githubusercontent.com/ user-images.githubusercontent.com/ private-user-images.githubusercontent.com opengraph.githubassets.com github-production-user-asset-6210df.s3.amazonaws.com customer-stories-feed.github.com spotlights-feed.github.com objects-origin.githubusercontent.com *.githubusercontent.com; manifest-src 'self'; media-src github.com user-images.githubusercontent.com/ secured-user-images.githubusercontent.com/ private-user-images.githubusercontent.com github-production-user-asset-6210df.s3.amazonaws.com gist.github.com; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com; upgrade-insecure-requests; worker-src github.com/assets-cdn/worker/ github.com/webpack/ github.com/assets/ gist.github.com/assets-cdn/worker/
Accept-Ranges: bytes
Set-Cookie: _gh_sess=tuy%2F6g6JkNcQm4TDXIzC9GK8VbW3dzljQkv5KjSCn6HAtxbdEtMUjjFbxpDECm1I11beLGk%2BCIyW3v%2BYNe7GDq%2Bt7eSXguAhVDQ8jRhi4VN9upQxTrKpm7R3ltWyJXSaJq7AvlCe2AgEu5x2A8gOJypVyJ6cCz7F5aeHZPRdduXUs%2BMAs3nA5RmJ8KtiJS8XreJ0EV2o8lyn2MFKL2Qdv4muo3HSr2aQSzjUXYMVHneCmQ3RvNMQFm%2BIi6La02l3DT9huxqnhhgEZpg%2FAM7xJQ%3D%3D--474OVNX%2BR3RBOdzF--3cSaWppOUOX21LrJaC4w8A%3D%3D; Path=/; HttpOnly; Secure; SameSite=Lax
Set-Cookie: _octo=GH1.1.2011471241.1739168906; Path=/; Domain=github.com; Expires=Tue, 10 Feb 2026 06:28:26 GMT; Secure; SameSite=Lax
Set-Cookie: logged_in=no; Path=/; Domain=github.com; Expires=Tue, 10 Feb 2026 06:28:26 GMT; HttpOnly; Secure; SameSite=Lax
X-GitHub-Request-Id: DA41:B193E:160E185:1D4E016:67A99C8A
connection: close
Transfer-Encoding: chunked

]
[2025-02-09 23:31:09,147: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-09 23:31:09,149: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-09 23:31:09,150: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-09 23:31:09,151: INFO: common: created directory at: artifacts]
[2025-02-09 23:31:09,151: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-09 23:31:10,610: INFO: 329861637: artifacts/data_ingestion/data.zip download with following info: /nConnection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 157E:FE6CA:BF9245:D7CD65:67A99D2F
Accept-Ranges: bytes
Date: Mon, 10 Feb 2025 06:31:11 GMT
Via: 1.1 varnish
X-Served-By: cache-den-kden1300040-DEN
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1739169072.932351,VS0,VE54
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 66c1271a0b8e652a415db1480de8749b9064354b
Expires: Mon, 10 Feb 2025 06:36:11 GMT
Source-Age: 0

]
[2025-02-10 10:19:46,405: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2025-02-10 10:19:46,413: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-10 10:19:46,417: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-10 10:19:46,418: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-10 10:19:46,418: INFO: common: created directory at: artifacts]
[2025-02-10 10:19:46,419: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-10 10:19:47,254: INFO: data_ingestion: artifacts/data_ingestion/data.zip download with following info: /nConnection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 088C:3CCAB3:9F4A5:ABEF8:67AA3533
Accept-Ranges: bytes
Date: Mon, 10 Feb 2025 17:19:47 GMT
Via: 1.1 varnish
X-Served-By: cache-den-kden1300034-DEN
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1739207987.344847,VS0,VE152
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 28438268a54b05bffb68f6433223249e63bc204e
Expires: Mon, 10 Feb 2025 17:24:47 GMT
Source-Age: 0

]
[2025-02-10 10:19:47,265: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<]
[2025-02-10 12:05:53,224: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-10 12:05:53,224: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-10 12:05:53,227: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-10 12:05:53,227: INFO: common: created directory at: artifacts]
[2025-02-10 12:05:53,227: INFO: common: created directory at: artifacts/data_validation]
[2025-02-10 12:07:38,207: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-10 12:07:38,208: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-10 12:07:38,211: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-10 12:07:38,212: INFO: common: created directory at: artifacts]
[2025-02-10 12:07:38,213: INFO: common: created directory at: artifacts/data_validation]
[2025-02-10 12:08:40,047: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-10 12:08:40,052: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-10 12:08:40,055: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-10 12:08:40,055: INFO: common: created directory at: artifacts]
[2025-02-10 12:08:40,055: INFO: common: created directory at: artifacts/data_validation]
[2025-02-10 12:13:46,863: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-10 12:13:46,864: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-10 12:13:46,867: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-10 12:13:46,868: INFO: common: created directory at: artifacts]
[2025-02-10 12:13:46,869: INFO: common: created directory at: artifacts/data_validation]
[2025-02-10 12:14:26,695: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-10 12:14:26,695: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-10 12:14:26,701: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-10 12:14:26,704: INFO: common: created directory at: artifacts]
[2025-02-10 12:14:26,704: INFO: common: created directory at: artifacts/data_validation]
[2025-02-10 12:14:53,907: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-10 12:14:53,907: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-10 12:14:53,907: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-10 12:14:53,907: INFO: common: created directory at: artifacts]
[2025-02-10 12:14:53,907: INFO: common: created directory at: artifacts/data_validation]
[2025-02-10 13:08:46,607: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2025-02-10 13:08:46,611: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-10 13:08:46,611: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-10 13:08:46,613: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-10 13:08:46,614: INFO: common: created directory at: artifacts]
[2025-02-10 13:08:46,614: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-10 13:08:46,614: INFO: data_ingestion: File already exists]
[2025-02-10 13:08:46,616: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<]
[2025-02-10 13:08:46,616: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2025-02-10 13:08:46,617: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-10 13:08:46,618: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-10 13:08:46,620: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-10 13:08:46,620: INFO: common: created directory at: artifacts]
[2025-02-10 13:08:46,620: INFO: common: created directory at: artifacts/data_validation]
[2025-02-10 13:08:46,640: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<]
[2025-02-11 13:21:09,633: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 13:21:09,639: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 13:21:09,647: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 13:21:09,648: INFO: common: created directory at: artifacts]
[2025-02-11 13:21:09,649: INFO: common: created directory at: artifacts/data_transformation]
[2025-02-11 13:21:49,659: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 13:21:49,661: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 13:21:49,664: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 13:21:49,665: INFO: common: created directory at: artifacts]
[2025-02-11 13:21:49,666: INFO: common: created directory at: artifacts/data_transformation]
[2025-02-11 13:21:49,693: INFO: 2043822624: splitted data into train and test sets]
[2025-02-11 13:21:49,694: INFO: 2043822624: (1199, 12)]
[2025-02-11 13:21:49,695: INFO: 2043822624: (400, 12)]
[2025-02-11 13:30:27,659: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2025-02-11 13:30:27,662: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 13:30:27,662: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 13:30:27,664: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 13:30:27,665: INFO: common: created directory at: artifacts]
[2025-02-11 13:30:27,665: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-11 13:30:27,665: INFO: data_ingestion: File already exists]
[2025-02-11 13:30:27,676: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<]
[2025-02-11 13:30:27,676: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2025-02-11 13:30:27,678: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 13:30:27,678: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 13:30:27,680: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 13:30:27,681: INFO: common: created directory at: artifacts]
[2025-02-11 13:30:27,681: INFO: common: created directory at: artifacts/data_transformation]
[2025-02-11 13:30:27,681: ERROR: main: 'DataTransformationConfig' object has no attribute 'unzip_data_dir']
Traceback (most recent call last):
  File "D:\TJ GT\udemy_mlops\S18_End_to_end\Udemy_endTOend\main.py", line 19, in <module>
    obj.initiate_data_validation()
  File "D:\TJ GT\udemy_mlops\S18_End_to_end\Udemy_endTOend\src\Udemy_endTOend\pipeline\data_validation_pipeline.py", line 15, in initiate_data_validation
    data_validation.validate_all_columns()
  File "D:\TJ GT\udemy_mlops\S18_End_to_end\Udemy_endTOend\src\Udemy_endTOend\components\data_validation.py", line 28, in validate_all_columns
    raise e
  File "D:\TJ GT\udemy_mlops\S18_End_to_end\Udemy_endTOend\src\Udemy_endTOend\components\data_validation.py", line 13, in validate_all_columns
    data = pd.read_csv(self.config.unzip_data_dir)
AttributeError: 'DataTransformationConfig' object has no attribute 'unzip_data_dir'
[2025-02-11 13:32:09,933: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2025-02-11 13:32:09,936: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 13:32:09,936: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 13:32:09,938: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 13:32:09,939: INFO: common: created directory at: artifacts]
[2025-02-11 13:32:09,939: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-11 13:32:09,939: INFO: data_ingestion: File already exists]
[2025-02-11 13:32:09,941: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<]
[2025-02-11 13:32:09,941: INFO: main: >>>>> stage Data Validation Stage started <<<<<]
[2025-02-11 13:32:09,943: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 13:32:09,944: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 13:32:09,946: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 13:32:09,946: INFO: common: created directory at: artifacts]
[2025-02-11 13:32:09,946: INFO: common: created directory at: artifacts/data_transformation]
[2025-02-11 13:32:09,946: ERROR: main: 'DataTransformationConfig' object has no attribute 'unzip_data_dir']
Traceback (most recent call last):
  File "D:\TJ GT\udemy_mlops\S18_End_to_end\Udemy_endTOend\main.py", line 20, in <module>
    obj.initiate_data_validation()
  File "D:\TJ GT\udemy_mlops\S18_End_to_end\Udemy_endTOend\src\Udemy_endTOend\pipeline\data_validation_pipeline.py", line 15, in initiate_data_validation
    data_validation.validate_all_columns()
  File "D:\TJ GT\udemy_mlops\S18_End_to_end\Udemy_endTOend\src\Udemy_endTOend\components\data_validation.py", line 28, in validate_all_columns
    raise e
  File "D:\TJ GT\udemy_mlops\S18_End_to_end\Udemy_endTOend\src\Udemy_endTOend\components\data_validation.py", line 13, in validate_all_columns
    data = pd.read_csv(self.config.unzip_data_dir)
AttributeError: 'DataTransformationConfig' object has no attribute 'unzip_data_dir'
[2025-02-11 13:34:14,365: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2025-02-11 13:34:14,367: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 13:34:14,368: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 13:34:14,370: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 13:34:14,370: INFO: common: created directory at: artifacts]
[2025-02-11 13:34:14,370: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-11 13:34:14,370: INFO: data_ingestion: File already exists]
[2025-02-11 13:34:14,374: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<]
[2025-02-11 13:34:14,375: INFO: main: >>>>> stage Data Validation Stage started <<<<<]
[2025-02-11 13:34:14,377: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 13:34:14,377: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 13:34:14,379: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 13:34:14,380: INFO: common: created directory at: artifacts]
[2025-02-11 13:34:14,380: INFO: common: created directory at: artifacts/data_validation]
[2025-02-11 13:34:14,405: INFO: main: >>>>> stage Data Validation Stage completed <<<<<]
[2025-02-11 13:34:14,405: INFO: main: >>>>> stage Data Transformation Stage started <<<<<]
[2025-02-11 13:34:14,407: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 13:34:14,408: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 13:34:14,410: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 13:34:14,410: INFO: common: created directory at: artifacts]
[2025-02-11 13:34:14,410: INFO: common: created directory at: artifacts/data_transformation]
[2025-02-11 13:34:14,410: ERROR: main: 'DataTransformation' object has no attribute 'validate_all_columns']
Traceback (most recent call last):
  File "D:\TJ GT\udemy_mlops\S18_End_to_end\Udemy_endTOend\main.py", line 30, in <module>
    obj.initiate_data_transformation()
  File "D:\TJ GT\udemy_mlops\S18_End_to_end\Udemy_endTOend\src\Udemy_endTOend\pipeline\data_transformation_pipeline.py", line 15, in initiate_data_transformation
    data_transformation.validate_all_columns()
AttributeError: 'DataTransformation' object has no attribute 'validate_all_columns'
[2025-02-11 13:34:56,390: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2025-02-11 13:34:56,392: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 13:34:56,392: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 13:34:56,396: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 13:34:56,396: INFO: common: created directory at: artifacts]
[2025-02-11 13:34:56,396: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-11 13:34:56,396: INFO: data_ingestion: File already exists]
[2025-02-11 13:34:56,398: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<]
[2025-02-11 13:34:56,398: INFO: main: >>>>> stage Data Validation Stage started <<<<<]
[2025-02-11 13:34:56,400: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 13:34:56,400: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 13:34:56,402: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 13:34:56,403: INFO: common: created directory at: artifacts]
[2025-02-11 13:34:56,403: INFO: common: created directory at: artifacts/data_validation]
[2025-02-11 13:34:56,421: INFO: main: >>>>> stage Data Validation Stage completed <<<<<]
[2025-02-11 13:34:56,421: INFO: main: >>>>> stage Data Transformation Stage started <<<<<]
[2025-02-11 13:34:56,423: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 13:34:56,424: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 13:34:56,426: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 13:34:56,426: INFO: common: created directory at: artifacts]
[2025-02-11 13:34:56,426: INFO: common: created directory at: artifacts/data_transformation]
[2025-02-11 13:34:56,443: INFO: data_transformation: splitted data into train and test sets]
[2025-02-11 13:34:56,443: INFO: data_transformation: (1199, 12)]
[2025-02-11 13:34:56,443: INFO: data_transformation: (400, 12)]
[2025-02-11 13:34:56,443: INFO: main: >>>>> stage Data Transformation Stage completed <<<<<]
[2025-02-11 14:35:47,520: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2025-02-11 14:35:47,523: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 14:35:47,524: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 14:35:47,526: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 14:35:47,526: INFO: common: created directory at: artifacts]
[2025-02-11 14:35:47,527: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-11 14:35:47,527: INFO: data_ingestion: File already exists]
[2025-02-11 14:35:47,528: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<]
[2025-02-11 14:35:47,528: INFO: main: >>>>> stage Data Validation Stage started <<<<<]
[2025-02-11 14:35:47,531: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 14:35:47,531: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 14:35:47,533: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 14:35:47,534: INFO: common: created directory at: artifacts]
[2025-02-11 14:35:47,534: INFO: common: created directory at: artifacts/data_validation]
[2025-02-11 14:35:47,551: INFO: main: >>>>> stage Data Validation Stage completed <<<<<]
[2025-02-11 14:35:47,552: INFO: main: >>>>> stage Data Transformation Stage started <<<<<]
[2025-02-11 14:35:47,554: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 14:35:47,555: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 14:35:47,558: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 14:35:47,558: INFO: common: created directory at: artifacts]
[2025-02-11 14:35:47,558: INFO: common: created directory at: artifacts/data_transformation]
[2025-02-11 14:35:47,574: INFO: data_transformation: splitted data into train and test sets]
[2025-02-11 14:35:47,574: INFO: data_transformation: (1199, 12)]
[2025-02-11 14:35:47,574: INFO: data_transformation: (400, 12)]
[2025-02-11 14:35:47,575: INFO: main: >>>>> stage Data Transformation Stage completed <<<<<]
[2025-02-11 14:35:47,575: INFO: main: >>>>> stage Model Training Stage started <<<<<]
[2025-02-11 14:35:47,578: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 14:35:47,579: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 14:35:47,581: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 14:35:47,581: INFO: common: created directory at: artifacts]
[2025-02-11 14:35:47,581: INFO: common: created directory at: artifacts/model_trainer]
[2025-02-11 14:35:47,582: ERROR: main: "'ConfigBox' object has no attribute 'l1_raio'"]
Traceback (most recent call last):
  File "box\\box.py", line 594, in box.box.Box.__getitem__
KeyError: 'l1_raio'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\box.py", line 633, in box.box.Box.__getattr__
  File "box\\box.py", line 621, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'l1_raio'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 635, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'l1_raio'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\config_box.py", line 29, in box.config_box.ConfigBox.__getattr__
  File "box\\box.py", line 649, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'l1_raio'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 594, in box.box.Box.__getitem__
KeyError: 'l1_raio'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\box.py", line 633, in box.box.Box.__getattr__
  File "box\\box.py", line 621, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'l1_raio'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 635, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'l1_raio'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\TJ GT\udemy_mlops\S18_End_to_end\Udemy_endTOend\main.py", line 41, in <module>
    obj.initiate_model_trainer()
  File "D:\TJ GT\udemy_mlops\S18_End_to_end\Udemy_endTOend\src\Udemy_endTOend\pipeline\model_trainer_pipeline.py", line 13, in initiate_model_trainer
    model_trainer_config = config.get_model_trainer_config()
  File "D:\TJ GT\udemy_mlops\S18_End_to_end\Udemy_endTOend\src\Udemy_endTOend\config\configuration.py", line 67, in get_model_trainer_config
    l1_ratio= params.l1_raio,
  File "box\\config_box.py", line 31, in box.config_box.ConfigBox.__getattr__
  File "box\\box.py", line 649, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'l1_raio'"
[2025-02-11 14:36:16,536: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2025-02-11 14:36:16,540: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 14:36:16,541: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 14:36:16,543: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 14:36:16,543: INFO: common: created directory at: artifacts]
[2025-02-11 14:36:16,543: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-11 14:36:16,544: INFO: data_ingestion: File already exists]
[2025-02-11 14:36:16,545: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<]
[2025-02-11 14:36:16,545: INFO: main: >>>>> stage Data Validation Stage started <<<<<]
[2025-02-11 14:36:16,548: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 14:36:16,549: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 14:36:16,551: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 14:36:16,551: INFO: common: created directory at: artifacts]
[2025-02-11 14:36:16,551: INFO: common: created directory at: artifacts/data_validation]
[2025-02-11 14:36:16,570: INFO: main: >>>>> stage Data Validation Stage completed <<<<<]
[2025-02-11 14:36:16,570: INFO: main: >>>>> stage Data Transformation Stage started <<<<<]
[2025-02-11 14:36:16,573: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 14:36:16,574: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 14:36:16,576: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 14:36:16,576: INFO: common: created directory at: artifacts]
[2025-02-11 14:36:16,577: INFO: common: created directory at: artifacts/data_transformation]
[2025-02-11 14:36:16,594: INFO: data_transformation: splitted data into train and test sets]
[2025-02-11 14:36:16,594: INFO: data_transformation: (1199, 12)]
[2025-02-11 14:36:16,594: INFO: data_transformation: (400, 12)]
[2025-02-11 14:36:16,594: INFO: main: >>>>> stage Data Transformation Stage completed <<<<<]
[2025-02-11 14:36:16,594: INFO: main: >>>>> stage Model Training Stage started <<<<<]
[2025-02-11 14:36:16,597: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 14:36:16,597: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 14:36:16,599: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 14:36:16,600: INFO: common: created directory at: artifacts]
[2025-02-11 14:36:16,600: INFO: common: created directory at: artifacts/model_trainer]
[2025-02-11 14:36:16,600: ERROR: main: "'ConfigBox' object has no attribute 'target_column'"]
Traceback (most recent call last):
  File "box\\box.py", line 594, in box.box.Box.__getitem__
KeyError: 'TARGET_COLUMN'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\box.py", line 633, in box.box.Box.__getattr__
  File "box\\box.py", line 621, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'TARGET_COLUMN'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 635, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'TARGET_COLUMN'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\config_box.py", line 29, in box.config_box.ConfigBox.__getattr__
  File "box\\box.py", line 649, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'TARGET_COLUMN'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 594, in box.box.Box.__getitem__
KeyError: 'target_column'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\box.py", line 633, in box.box.Box.__getattr__
  File "box\\box.py", line 621, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'target_column'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 635, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'target_column'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\TJ GT\udemy_mlops\S18_End_to_end\Udemy_endTOend\main.py", line 41, in <module>
    obj.initiate_model_trainer()
  File "D:\TJ GT\udemy_mlops\S18_End_to_end\Udemy_endTOend\src\Udemy_endTOend\pipeline\model_trainer_pipeline.py", line 13, in initiate_model_trainer
    model_trainer_config = config.get_model_trainer_config()
  File "D:\TJ GT\udemy_mlops\S18_End_to_end\Udemy_endTOend\src\Udemy_endTOend\config\configuration.py", line 68, in get_model_trainer_config
    target_column=schema.TARGET_COLUMN
  File "box\\config_box.py", line 31, in box.config_box.ConfigBox.__getattr__
  File "box\\box.py", line 649, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'target_column'"
[2025-02-11 14:38:43,481: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2025-02-11 14:38:43,484: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 14:38:43,485: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 14:38:43,487: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 14:38:43,487: INFO: common: created directory at: artifacts]
[2025-02-11 14:38:43,487: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-11 14:38:43,487: INFO: data_ingestion: File already exists]
[2025-02-11 14:38:43,489: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<]
[2025-02-11 14:38:43,489: INFO: main: >>>>> stage Data Validation Stage started <<<<<]
[2025-02-11 14:38:43,492: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 14:38:43,493: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 14:38:43,495: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 14:38:43,495: INFO: common: created directory at: artifacts]
[2025-02-11 14:38:43,495: INFO: common: created directory at: artifacts/data_validation]
[2025-02-11 14:38:43,512: INFO: main: >>>>> stage Data Validation Stage completed <<<<<]
[2025-02-11 14:38:43,512: INFO: main: >>>>> stage Data Transformation Stage started <<<<<]
[2025-02-11 14:38:43,515: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 14:38:43,516: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 14:38:43,518: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 14:38:43,518: INFO: common: created directory at: artifacts]
[2025-02-11 14:38:43,518: INFO: common: created directory at: artifacts/data_transformation]
[2025-02-11 14:38:43,538: INFO: data_transformation: splitted data into train and test sets]
[2025-02-11 14:38:43,538: INFO: data_transformation: (1199, 12)]
[2025-02-11 14:38:43,538: INFO: data_transformation: (400, 12)]
[2025-02-11 14:38:43,538: INFO: main: >>>>> stage Data Transformation Stage completed <<<<<]
[2025-02-11 14:38:43,538: INFO: main: >>>>> stage Model Training Stage started <<<<<]
[2025-02-11 14:38:43,541: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 14:38:43,542: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 14:38:43,544: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 14:38:43,544: INFO: common: created directory at: artifacts]
[2025-02-11 14:38:43,544: INFO: common: created directory at: artifacts/model_trainer]
[2025-02-11 14:38:43,545: ERROR: main: 'NoneType' object has no attribute 'train_data_path']
Traceback (most recent call last):
  File "D:\TJ GT\udemy_mlops\S18_End_to_end\Udemy_endTOend\main.py", line 41, in <module>
    obj.initiate_model_trainer()
  File "D:\TJ GT\udemy_mlops\S18_End_to_end\Udemy_endTOend\src\Udemy_endTOend\pipeline\model_trainer_pipeline.py", line 15, in initiate_model_trainer
    model_trainer.train()
  File "D:\TJ GT\udemy_mlops\S18_End_to_end\Udemy_endTOend\src\Udemy_endTOend\components\model_trainer.py", line 13, in train
    train_data = pd.read_csv(self.config.train_data_path)
AttributeError: 'NoneType' object has no attribute 'train_data_path'
[2025-02-11 14:46:20,911: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2025-02-11 14:46:20,914: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 14:46:20,915: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 14:46:20,917: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 14:46:20,918: INFO: common: created directory at: artifacts]
[2025-02-11 14:46:20,918: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-11 14:46:20,918: INFO: data_ingestion: File already exists]
[2025-02-11 14:46:20,920: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<]
[2025-02-11 14:46:20,920: INFO: main: >>>>> stage Data Validation Stage started <<<<<]
[2025-02-11 14:46:20,922: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 14:46:20,923: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 14:46:20,925: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 14:46:20,925: INFO: common: created directory at: artifacts]
[2025-02-11 14:46:20,926: INFO: common: created directory at: artifacts/data_validation]
[2025-02-11 14:46:20,943: INFO: main: >>>>> stage Data Validation Stage completed <<<<<]
[2025-02-11 14:46:20,943: INFO: main: >>>>> stage Data Transformation Stage started <<<<<]
[2025-02-11 14:46:20,946: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 14:46:20,947: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 14:46:20,949: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 14:46:20,949: INFO: common: created directory at: artifacts]
[2025-02-11 14:46:20,949: INFO: common: created directory at: artifacts/data_transformation]
[2025-02-11 14:46:20,966: INFO: data_transformation: splitted data into train and test sets]
[2025-02-11 14:46:20,966: INFO: data_transformation: (1199, 12)]
[2025-02-11 14:46:20,966: INFO: data_transformation: (400, 12)]
[2025-02-11 14:46:20,966: INFO: main: >>>>> stage Data Transformation Stage completed <<<<<]
[2025-02-11 14:46:20,966: INFO: main: >>>>> stage Model Training Stage started <<<<<]
[2025-02-11 14:46:20,969: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 14:46:20,970: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 14:46:20,972: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 14:46:20,972: INFO: common: created directory at: artifacts]
[2025-02-11 14:46:20,972: INFO: common: created directory at: artifacts/model_trainer]
[2025-02-11 14:46:20,995: INFO: main: >>>>> stage Model Training Stage completed <<<<<]
[2025-02-11 16:56:47,705: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2025-02-11 16:56:47,709: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 16:56:47,710: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 16:56:47,712: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 16:56:47,712: INFO: common: created directory at: artifacts]
[2025-02-11 16:56:47,713: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-11 16:56:47,713: INFO: data_ingestion: File already exists]
[2025-02-11 16:56:47,717: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<]
[2025-02-11 16:56:47,718: INFO: main: >>>>> stage Data Validation Stage started <<<<<]
[2025-02-11 16:56:47,725: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 16:56:47,726: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 16:56:47,728: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 16:56:47,728: INFO: common: created directory at: artifacts]
[2025-02-11 16:56:47,729: INFO: common: created directory at: artifacts/data_validation]
[2025-02-11 16:56:47,746: INFO: main: >>>>> stage Data Validation Stage completed <<<<<]
[2025-02-11 16:56:47,746: INFO: main: >>>>> stage Data Transformation Stage started <<<<<]
[2025-02-11 16:56:47,749: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 16:56:47,751: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 16:56:47,753: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 16:56:47,753: INFO: common: created directory at: artifacts]
[2025-02-11 16:56:47,753: INFO: common: created directory at: artifacts/data_transformation]
[2025-02-11 16:56:47,769: INFO: data_transformation: splitted data into train and test sets]
[2025-02-11 16:56:47,769: INFO: data_transformation: (1199, 12)]
[2025-02-11 16:56:47,770: INFO: data_transformation: (400, 12)]
[2025-02-11 16:56:47,770: INFO: main: >>>>> stage Data Transformation Stage completed <<<<<]
[2025-02-11 16:56:47,770: INFO: main: >>>>> stage Model Training Stage started <<<<<]
[2025-02-11 16:56:47,773: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 16:56:47,774: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 16:56:47,776: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 16:56:47,776: INFO: common: created directory at: artifacts]
[2025-02-11 16:56:47,776: INFO: common: created directory at: artifacts/model_trainer]
[2025-02-11 16:56:47,802: INFO: main: >>>>> stage Model Training Stage completed <<<<<]
[2025-02-11 16:56:47,803: INFO: main: >>>>> stage Model Evaluation Stage started <<<<<]
[2025-02-11 16:56:47,806: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 16:56:47,806: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 16:56:47,808: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 16:56:47,809: INFO: common: created directory at: artifacts]
[2025-02-11 16:56:47,809: ERROR: main: "'ConfigBox' object has no attribute 'model_evaluaion'"]
Traceback (most recent call last):
  File "box\\box.py", line 594, in box.box.Box.__getitem__
KeyError: 'model_evaluaion'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\box.py", line 633, in box.box.Box.__getattr__
  File "box\\box.py", line 621, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'model_evaluaion'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 635, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'model_evaluaion'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\config_box.py", line 29, in box.config_box.ConfigBox.__getattr__
  File "box\\box.py", line 649, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'model_evaluaion'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 594, in box.box.Box.__getitem__
KeyError: 'model_evaluaion'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\box.py", line 633, in box.box.Box.__getattr__
  File "box\\box.py", line 621, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'model_evaluaion'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 635, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'model_evaluaion'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\TJ GT\udemy_mlops\S18_End_to_end\Udemy_endTOend\main.py", line 52, in <module>
    obj.initiate_model_evaluation()
  File "D:\TJ GT\udemy_mlops\S18_End_to_end\Udemy_endTOend\src\Udemy_endTOend\pipeline\model_evaluation_pipeline.py", line 13, in initiate_model_evaluation
    model_evaluation_config = config.get_model_evaluation_config()
  File "D:\TJ GT\udemy_mlops\S18_End_to_end\Udemy_endTOend\src\Udemy_endTOend\config\configuration.py", line 74, in get_model_evaluation_config
    config = self.config.model_evaluaion
  File "box\\config_box.py", line 31, in box.config_box.ConfigBox.__getattr__
  File "box\\box.py", line 649, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'model_evaluaion'"
[2025-02-11 16:57:48,424: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2025-02-11 16:57:48,428: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 16:57:48,429: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 16:57:48,431: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 16:57:48,431: INFO: common: created directory at: artifacts]
[2025-02-11 16:57:48,431: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-11 16:57:48,431: INFO: data_ingestion: File already exists]
[2025-02-11 16:57:48,433: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<]
[2025-02-11 16:57:48,433: INFO: main: >>>>> stage Data Validation Stage started <<<<<]
[2025-02-11 16:57:48,437: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 16:57:48,438: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 16:57:48,440: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 16:57:48,440: INFO: common: created directory at: artifacts]
[2025-02-11 16:57:48,440: INFO: common: created directory at: artifacts/data_validation]
[2025-02-11 16:57:48,460: INFO: main: >>>>> stage Data Validation Stage completed <<<<<]
[2025-02-11 16:57:48,460: INFO: main: >>>>> stage Data Transformation Stage started <<<<<]
[2025-02-11 16:57:48,464: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 16:57:48,465: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 16:57:48,467: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 16:57:48,467: INFO: common: created directory at: artifacts]
[2025-02-11 16:57:48,467: INFO: common: created directory at: artifacts/data_transformation]
[2025-02-11 16:57:48,483: INFO: data_transformation: splitted data into train and test sets]
[2025-02-11 16:57:48,483: INFO: data_transformation: (1199, 12)]
[2025-02-11 16:57:48,483: INFO: data_transformation: (400, 12)]
[2025-02-11 16:57:48,483: INFO: main: >>>>> stage Data Transformation Stage completed <<<<<]
[2025-02-11 16:57:48,483: INFO: main: >>>>> stage Model Training Stage started <<<<<]
[2025-02-11 16:57:48,487: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 16:57:48,487: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 16:57:48,489: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 16:57:48,490: INFO: common: created directory at: artifacts]
[2025-02-11 16:57:48,490: INFO: common: created directory at: artifacts/model_trainer]
[2025-02-11 16:57:48,513: INFO: main: >>>>> stage Model Training Stage completed <<<<<]
[2025-02-11 16:57:48,513: INFO: main: >>>>> stage Model Evaluation Stage started <<<<<]
[2025-02-11 16:57:48,516: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-11 16:57:48,517: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-11 16:57:48,519: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-02-11 16:57:48,519: INFO: common: created directory at: artifacts]
[2025-02-11 16:57:48,519: INFO: common: created directory at: artifacts/model_evaluation]
[2025-02-11 16:57:48,531: INFO: common: json file saved at: artifacts\model_evaluation\metrics.json]
[2025-02-11 16:57:48,531: INFO: main: >>>>> stage Model Evaluation Stage completed <<<<<]
